### ISSUE TITLE
Development in back-end GUI (Calendar )

### ISSUE THREAD

**Issue by terr133** [Echilled/INF2001-P10-group2#3]
Developing a backend system that checks based on the availability of response staff in a calender view: 
- Checks all shifts if the manpower is fulfilled across all roles
- Allows the role 'Manager' having the ability to change timeslots for staff
- Allows the role 'Manager' to edit the staff for each shift
- Informs the manager if the manpower is lacking for any shifts

Goals: Provides the manager the ability to consolidate the manpower into a single space for viewing convenience. 

Allocated Time: 4 weeks

Start date: 25/9/23
End date: 25/10/23

**Comment by jackysim99** [comment]
Added back end GUI for calendar
Work has been commited
Work completion is in line with project deadline
No changes to the susccess or completion criteria of the task
25/09/23 227/09/23
