### ISSUE TITLE
Job allocation page design planning (Back-End)

### ISSUE THREAD

**Issue by terr133** [Echilled/INF2001-P10-group2#9]
Creation of the back-end functionalities to communicate and handle any front-end requests from the front end of the job allocation page. 

Completion Criteria: The backend is successful is retrieving the information to meet the requests from the front end properly.

Allocated Time: 4 weeks 

Start date: 25/9/23
Expected End date: 25/10/23

**Comment by jackysim99** [comment]
Added job allocation page design
Work has been commited
Work completion is in line with project deadline
No changes to the susccess or completion criteria of the task
22/09/23 25/09/23
